# Generated by Django 3.1.2 on 2020-11-02 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=255)),
                ('league_country', models.CharField(max_length=255)),
                ('league_logo', models.URLField(blank=True, max_length=255)),
                ('league_flag', models.URLField(blank=True, max_length=255)),
                ('date', models.DateTimeField(blank=True)),
                ('hour', models.TimeField()),
                ('round', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('venue', models.CharField(max_length=255, null=True)),
                ('home_team_name', models.CharField(max_length=255)),
                ('home_team_logo', models.URLField(blank=True, max_length=255)),
                ('goals_home_team', models.IntegerField(null=True)),
                ('away_team_name', models.CharField(max_length=255, null=True)),
                ('away_team_logo', models.URLField(blank=True, max_length=255)),
                ('goals_away_team', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, null=True)),
                ('logo', models.URLField(blank=True, max_length=255)),
                ('country', models.CharField(max_length=255, null=True)),
                ('is_national', models.BooleanField(default=False)),
                ('founded', models.IntegerField(null=True)),
                ('venue_name', models.CharField(max_length=255, null=True)),
                ('venue_surface', models.CharField(max_length=255, null=True)),
                ('venue_address', models.CharField(max_length=255, null=True)),
                ('venue_city', models.CharField(max_length=255, null=True)),
                ('venue_capacity', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('endpoint', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(choices=[('Webhook', 'Webhook'), ('Email', 'Email')], max_length=10)),
                ('frequency', models.CharField(choices=[('Week', 'Weekly'), ('Day', 'Daily'), ('Live', 'Live')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notificator.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
