# Generated by Django 3.1.2 on 2020-11-02 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificator', '0003_auto_20201102_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='league_flag',
        ),
    ]
