# Generated by Django 3.1.2 on 2020-11-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificator', '0004_remove_event_league_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
