# Generated by Django 3.1.2 on 2020-11-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificator', '0005_auto_20201102_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Webhook', 'Webhook'), ('Email', 'Email')], db_index=True, max_length=10),
        ),
    ]
